// <auto-generated />
using System;
using ExaminationSystemDB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExaminationSystemDB.Migrations
{
    [DbContext(typeof(ExamContext))]
    [Migration("20250628032813_Seeding data")]
    partial class Seedingdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExaminationSystemDB.Models.Answer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answer");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AnswerText = "Programming Language",
                            IsCorrect = true,
                            QuestionId = 1
                        },
                        new
                        {
                            ID = 2,
                            AnswerText = "Markup Language",
                            IsCorrect = false,
                            QuestionId = 1
                        },
                        new
                        {
                            ID = 3,
                            AnswerText = "4",
                            IsCorrect = true,
                            QuestionId = 2
                        },
                        new
                        {
                            ID = 4,
                            AnswerText = "22",
                            IsCorrect = false,
                            QuestionId = 2
                        },
                        new
                        {
                            ID = 5,
                            AnswerText = "Framework",
                            IsCorrect = true,
                            QuestionId = 3
                        },
                        new
                        {
                            ID = 6,
                            AnswerText = "Language",
                            IsCorrect = false,
                            QuestionId = 3
                        },
                        new
                        {
                            ID = 7,
                            AnswerText = "Common Language Runtime",
                            IsCorrect = true,
                            QuestionId = 4
                        },
                        new
                        {
                            ID = 8,
                            AnswerText = "Code Line Reader",
                            IsCorrect = false,
                            QuestionId = 4
                        });
                });

            modelBuilder.Entity("ExaminationSystemDB.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("MinGrade")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Exam");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = 60,
                            Grade = 100,
                            MinGrade = 50,
                            Name = "C# Basics"
                        },
                        new
                        {
                            Id = 2,
                            Duration = 90,
                            Grade = 100,
                            MinGrade = 60,
                            Name = ".NET Fundamentals"
                        });
                });

            modelBuilder.Entity("ExaminationSystemDB.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("Question");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "What is C#?",
                            ExamId = 1,
                            Grade = 10,
                            Type = "MCQ"
                        },
                        new
                        {
                            Id = 2,
                            Body = "What is the output of Console.WriteLine(2+2)?",
                            ExamId = 1,
                            Grade = 10,
                            Type = "MCQ"
                        },
                        new
                        {
                            Id = 3,
                            Body = "What is .NET?",
                            ExamId = 2,
                            Grade = 10,
                            Type = "MCQ"
                        },
                        new
                        {
                            Id = 4,
                            Body = "What is CLR?",
                            ExamId = 2,
                            Grade = 10,
                            Type = "MCQ"
                        });
                });

            modelBuilder.Entity("ExaminationSystemDB.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "Benha",
                            Email = "abdelrahman@example.com",
                            HashedPassword = "hashed123",
                            Name = "AbdelRahman"
                        },
                        new
                        {
                            ID = 2,
                            Address = "Cairo",
                            Email = "sara@example.com",
                            HashedPassword = "sara123",
                            Name = "Sara Ahmed"
                        },
                        new
                        {
                            ID = 3,
                            Address = "Alexandria",
                            Email = "omar@example.com",
                            HashedPassword = "omar123",
                            Name = "Omar Tarek"
                        });
                });

            modelBuilder.Entity("ExaminationSystemDB.Models.StudentAnswer", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "QuestionId", "AnswerId");

                    b.HasIndex("AnswerId");

                    b.HasIndex("QuestionId");

                    b.ToTable("StudentAnswer");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            QuestionId = 1,
                            AnswerId = 1
                        },
                        new
                        {
                            StudentId = 1,
                            QuestionId = 2,
                            AnswerId = 3
                        },
                        new
                        {
                            StudentId = 2,
                            QuestionId = 3,
                            AnswerId = 5
                        },
                        new
                        {
                            StudentId = 2,
                            QuestionId = 4,
                            AnswerId = 7
                        },
                        new
                        {
                            StudentId = 3,
                            QuestionId = 1,
                            AnswerId = 2
                        });
                });

            modelBuilder.Entity("ExaminationSystemDB.Models.StudentExam", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("StudentGrade")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "ExamId");

                    b.HasIndex("ExamId");

                    b.ToTable("StudentExam");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            ExamId = 1,
                            EndTime = new DateTime(2025, 6, 28, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 6, 28, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentGrade = 90
                        },
                        new
                        {
                            StudentId = 2,
                            ExamId = 2,
                            EndTime = new DateTime(2025, 6, 29, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2025, 6, 29, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentGrade = 85
                        });
                });

            modelBuilder.Entity("ExaminationSystemDB.Models.Answer", b =>
                {
                    b.HasOne("ExaminationSystemDB.Models.Question", "question")
                        .WithMany("answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("question");
                });

            modelBuilder.Entity("ExaminationSystemDB.Models.Question", b =>
                {
                    b.HasOne("ExaminationSystemDB.Models.Exam", "exam")
                        .WithMany("question")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("exam");
                });

            modelBuilder.Entity("ExaminationSystemDB.Models.StudentAnswer", b =>
                {
                    b.HasOne("ExaminationSystemDB.Models.Answer", "answer")
                        .WithMany("studentAnswer")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExaminationSystemDB.Models.Question", "question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExaminationSystemDB.Models.Student", "student")
                        .WithMany("studentAnswer")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("answer");

                    b.Navigation("question");

                    b.Navigation("student");
                });

            modelBuilder.Entity("ExaminationSystemDB.Models.StudentExam", b =>
                {
                    b.HasOne("ExaminationSystemDB.Models.Exam", "exam")
                        .WithMany("studentExams")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExaminationSystemDB.Models.Student", "student")
                        .WithMany("studentExams")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("exam");

                    b.Navigation("student");
                });

            modelBuilder.Entity("ExaminationSystemDB.Models.Answer", b =>
                {
                    b.Navigation("studentAnswer");
                });

            modelBuilder.Entity("ExaminationSystemDB.Models.Exam", b =>
                {
                    b.Navigation("question");

                    b.Navigation("studentExams");
                });

            modelBuilder.Entity("ExaminationSystemDB.Models.Question", b =>
                {
                    b.Navigation("answers");
                });

            modelBuilder.Entity("ExaminationSystemDB.Models.Student", b =>
                {
                    b.Navigation("studentAnswer");

                    b.Navigation("studentExams");
                });
#pragma warning restore 612, 618
        }
    }
}
